spawn:
  world: world
  x: 0
  y: 0
  z: 0
  yaw: 0.0
  pitch: 0.0
stats:
    maxHealth: 100.0
    health: 100.0
    armor: 0.0
    maxMana: 100.0
    mana: 100.0
    agility: 5
    strength: 5
    intelligent: 5